image: node:erbium-alpine

variables:
  DEPLOYER_TAG: "registry.gitlab.com/rphovley-templates/nextjs-typescript/deployer"

stages:
  - dependencies
  - build
  - staging
  - production

cache:
  key:
    files:
      - package.json
  paths:
    - node_modules/

dependencies:
  stage: dependencies
  script:
    - yarn
    - yarn lint
  only:
    changes:
      - package.json

build:
  stage: build
  script:
    - yarn build
    - yarn export
    - cd out && echo $CI_COMMIT_SHORT_SHA > VERSION
  artifacts:
    name: "$CI_COMMIT_SHORT_SHA-build"
    paths:
      - out

deploy_staging:
  stage: staging
  image: $DEPLOYER_TAG
  when: on_success
  environment: staging
  script:
    - firebase deploy --token $FIREBASE_TOKEN -P $PROJECT_ID

deploy_production:
  stage: production
  image: $DEPLOYER_TAG
  when: manual
  only:
    - master
  environment: production
  script:
    - firebase deploy --token "$FIREBASE_TOKEN" -P $PROJECT_ID
